
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'BlogList': typeof import("../../components/blog/blog-list.vue").default
  'BlogSidebar': typeof import("../../components/blog/blog-sidebar.vue").default
  'CartModalCartBottomModel': typeof import("../../components/cart-modal/cart-bottom-model.vue").default
  'CartModalCartLeftModel': typeof import("../../components/cart-modal/cart-left-model.vue").default
  'CartModalPopup': typeof import("../../components/cart-modal/cart-modal-popup.vue").default
  'CartModalCartRightModel': typeof import("../../components/cart-modal/cart-right-model.vue").default
  'CartModalCartTopModel': typeof import("../../components/cart-modal/cart-top-model.vue").default
  'FooterFooter2': typeof import("../../components/footer/footer2.vue").default
  'FooterFooter3': typeof import("../../components/footer/footer3.vue").default
  'FooterFooter4': typeof import("../../components/footer/footer4.vue").default
  'FooterFooter5': typeof import("../../components/footer/footer5.vue").default
  'FooterFooter6': typeof import("../../components/footer/footer6.vue").default
  'FooterFooter7': typeof import("../../components/footer/footer7.vue").default
  'Footer': typeof import("../../components/footer/index.vue").default
  'HeaderHeader2': typeof import("../../components/header/header2.vue").default
  'HeaderHeader3': typeof import("../../components/header/header3.vue").default
  'HeaderHeader4': typeof import("../../components/header/header4.vue").default
  'HeaderHeader5': typeof import("../../components/header/header5.vue").default
  'HeaderHeader6': typeof import("../../components/header/header6.vue").default
  'HeaderHeader7': typeof import("../../components/header/header7.vue").default
  'HeaderHeader8': typeof import("../../components/header/header8.vue").default
  'Header': typeof import("../../components/header/index.vue").default
  'LightBox': typeof import("../../components/lightBox.vue").default
  'PaymentPage': typeof import("../../components/paymentPage.vue").default
  'ProductBoxProductBox1': typeof import("../../components/product-box/product-box1.vue").default
  'ProductBoxProductBox2': typeof import("../../components/product-box/product-box2.vue").default
  'ProductBoxProductBox3': typeof import("../../components/product-box/product-box3.vue").default
  'ProductBoxProductBox4': typeof import("../../components/product-box/product-box4.vue").default
  'ProductBoxProductBox5': typeof import("../../components/product-box/product-box5.vue").default
  'ProductBoxProductBox6': typeof import("../../components/product-box/product-box6.vue").default
  'ProductBoxProductBox7': typeof import("../../components/product-box/product-box7.vue").default
  'ProductBoxProductBox8': typeof import("../../components/product-box/product-box8.vue").default
  'ProductBoxProductBox9': typeof import("../../components/product-box/product-box9.vue").default
  'Searched': typeof import("../../components/searched.vue").default
  'ShopBagsBanner': typeof import("../../components/shop/bags/banner.vue").default
  'ShopBagsBlog': typeof import("../../components/shop/bags/blog.vue").default
  'ShopBagsCategory': typeof import("../../components/shop/bags/category.vue").default
  'ShopBagsCategory2': typeof import("../../components/shop/bags/category2.vue").default
  'ShopBagsCategorytab': typeof import("../../components/shop/bags/categorytab.vue").default
  'ShopBagsInstagram': typeof import("../../components/shop/bags/instagram.vue").default
  'ShopBagsProductcategoryslider': typeof import("../../components/shop/bags/productcategoryslider.vue").default
  'ShopBagsProductslider': typeof import("../../components/shop/bags/productslider.vue").default
  'ShopBagsServices': typeof import("../../components/shop/bags/services.vue").default
  'ShopBagsSlider': typeof import("../../components/shop/bags/slider.vue").default
  'ShopBeautyAbout': typeof import("../../components/shop/beauty/about.vue").default
  'ShopBeautyBlog': typeof import("../../components/shop/beauty/blog.vue").default
  'ShopBeautyInstagram': typeof import("../../components/shop/beauty/instagram.vue").default
  'ShopBeautyProductSlider': typeof import("../../components/shop/beauty/product-slider.vue").default
  'ShopBeautySlider': typeof import("../../components/shop/beauty/slider.vue").default
  'ShopBeautyTopProductSlider': typeof import("../../components/shop/beauty/top-product-slider.vue").default
  'ShopBeautyVideoTutorial': typeof import("../../components/shop/beauty/video-tutorial.vue").default
  'ShopElectronics1CollectionBanner': typeof import("../../components/shop/electronics-1/collection_banner.vue").default
  'ShopElectronics1ProductTab': typeof import("../../components/shop/electronics-1/product_tab.vue").default
  'ShopElectronics1Slider': typeof import("../../components/shop/electronics-1/slider.vue").default
  'ShopFashion2Banner': typeof import("../../components/shop/fashion-2/banner.vue").default
  'ShopFashion2CollectionBanner': typeof import("../../components/shop/fashion-2/collection-banner.vue").default
  'ShopFashion2Collection': typeof import("../../components/shop/fashion-2/collection.vue").default
  'ShopFashion2Instagram': typeof import("../../components/shop/fashion-2/instagram.vue").default
  'ShopFashion2Product': typeof import("../../components/shop/fashion-2/product.vue").default
  'ShopFashion2Slider': typeof import("../../components/shop/fashion-2/slider.vue").default
  'ShopFashion3Banner': typeof import("../../components/shop/fashion-3/banner.vue").default
  'ShopFashion3ProductSlider': typeof import("../../components/shop/fashion-3/product_slider.vue").default
  'ShopFashion3ProductTab': typeof import("../../components/shop/fashion-3/product_tab.vue").default
  'ShopFashion3Slider': typeof import("../../components/shop/fashion-3/slider.vue").default
  'ShopFashionBanner': typeof import("../../components/shop/fashion/banner.vue").default
  'ShopFashionBlog': typeof import("../../components/shop/fashion/blog.vue").default
  'ShopFashionCollectionBanner': typeof import("../../components/shop/fashion/collection_banner.vue").default
  'ShopFashionInstagram': typeof import("../../components/shop/fashion/instagram.vue").default
  'ShopFashionLogoSlider': typeof import("../../components/shop/fashion/logo_slider.vue").default
  'ShopFashionProductSlider': typeof import("../../components/shop/fashion/product_slider.vue").default
  'ShopFashionProductTab': typeof import("../../components/shop/fashion/product_tab.vue").default
  'ShopFashionServices': typeof import("../../components/shop/fashion/services.vue").default
  'ShopFashionSlider': typeof import("../../components/shop/fashion/slider.vue").default
  'ShopFlowerBlog': typeof import("../../components/shop/flower/blog.vue").default
  'ShopFlowerCategoryTab': typeof import("../../components/shop/flower/category_tab.vue").default
  'ShopFlowerCollectionBanner': typeof import("../../components/shop/flower/collection_banner.vue").default
  'ShopFlowerInstagram': typeof import("../../components/shop/flower/instagram.vue").default
  'ShopFlowerProductSlider': typeof import("../../components/shop/flower/product_slider.vue").default
  'ShopFlowerServices': typeof import("../../components/shop/flower/services.vue").default
  'ShopFlowerSlider': typeof import("../../components/shop/flower/slider.vue").default
  'ShopFlowerTopProducts': typeof import("../../components/shop/flower/top_products.vue").default
  'ShopFurnitureBlog': typeof import("../../components/shop/furniture/blog.vue").default
  'ShopFurnitureCategoryTab': typeof import("../../components/shop/furniture/category_tab.vue").default
  'ShopFurnitureCollectionBanner': typeof import("../../components/shop/furniture/collection_banner.vue").default
  'ShopFurnitureParallaxBanner': typeof import("../../components/shop/furniture/parallax_banner.vue").default
  'ShopFurnitureSlider': typeof import("../../components/shop/furniture/slider.vue").default
  'ShopGymBlog': typeof import("../../components/shop/gym/blog.vue").default
  'ShopGymCollectionBanner': typeof import("../../components/shop/gym/collection-banner.vue").default
  'ShopGymInstagram': typeof import("../../components/shop/gym/instagram.vue").default
  'ShopGymLogoSlider': typeof import("../../components/shop/gym/logo-slider.vue").default
  'ShopGymProductList': typeof import("../../components/shop/gym/product-list.vue").default
  'ShopGymSlider': typeof import("../../components/shop/gym/slider.vue").default
  'ShopGymTopCollection': typeof import("../../components/shop/gym/top-collection.vue").default
  'ShopJewelleryCategory': typeof import("../../components/shop/jewellery/category.vue").default
  'ShopJewelleryInstagram': typeof import("../../components/shop/jewellery/instagram.vue").default
  'ShopJewelleryParallaxBanner': typeof import("../../components/shop/jewellery/parallax-banner.vue").default
  'ShopJewelleryProductSlider': typeof import("../../components/shop/jewellery/product-slider.vue").default
  'ShopJewelleryProductTab': typeof import("../../components/shop/jewellery/product-tab.vue").default
  'ShopJewelleryServices': typeof import("../../components/shop/jewellery/services.vue").default
  'ShopJewellerySlider': typeof import("../../components/shop/jewellery/slider.vue").default
  'ShopKidsCollectionBanner': typeof import("../../components/shop/kids/collection_banner.vue").default
  'ShopKidsCollectionSlider': typeof import("../../components/shop/kids/collection_slider.vue").default
  'ShopKidsInstagram': typeof import("../../components/shop/kids/instagram.vue").default
  'ShopKidsLogoSlider': typeof import("../../components/shop/kids/logo_slider.vue").default
  'ShopKidsParallaxBanner': typeof import("../../components/shop/kids/parallax_banner.vue").default
  'ShopKidsProductSlider': typeof import("../../components/shop/kids/product_slider.vue").default
  'ShopKidsSlider': typeof import("../../components/shop/kids/slider.vue").default
  'ShopPetsBlog': typeof import("../../components/shop/pets/blog.vue").default
  'ShopPetsCollectionBanner': typeof import("../../components/shop/pets/collection-banner.vue").default
  'ShopPetsLogoSlider': typeof import("../../components/shop/pets/logo-slider.vue").default
  'ShopPetsParallaxBanner': typeof import("../../components/shop/pets/parallax-banner.vue").default
  'ShopPetsProductSlider': typeof import("../../components/shop/pets/product-slider.vue").default
  'ShopPetsSlider': typeof import("../../components/shop/pets/slider.vue").default
  'ShopPetsTopCollection': typeof import("../../components/shop/pets/top-collection.vue").default
  'ShopShoesAbout': typeof import("../../components/shop/shoes/about.vue").default
  'ShopShoesBlog': typeof import("../../components/shop/shoes/blog.vue").default
  'ShopShoesBrand': typeof import("../../components/shop/shoes/brand.vue").default
  'ShopShoesCategory': typeof import("../../components/shop/shoes/category.vue").default
  'ShopShoesCategory2': typeof import("../../components/shop/shoes/category2.vue").default
  'ShopShoesCategory3': typeof import("../../components/shop/shoes/category3.vue").default
  'ShopShoesCollectionbanner': typeof import("../../components/shop/shoes/collectionbanner.vue").default
  'ShopShoesCollectionslider': typeof import("../../components/shop/shoes/collectionslider.vue").default
  'ShopShoesCollectiontab': typeof import("../../components/shop/shoes/collectiontab.vue").default
  'ShopShoesInstagram': typeof import("../../components/shop/shoes/instagram.vue").default
  'ShopShoesProductSlider': typeof import("../../components/shop/shoes/productSlider.vue").default
  'ShopShoesService': typeof import("../../components/shop/shoes/service.vue").default
  'ShopShoesSlider': typeof import("../../components/shop/shoes/slider.vue").default
  'ShopToolsAbout': typeof import("../../components/shop/tools/about.vue").default
  'ShopToolsCategory': typeof import("../../components/shop/tools/category.vue").default
  'ShopToolsLogoSlider': typeof import("../../components/shop/tools/logo_slider.vue").default
  'ShopToolsProductSlider': typeof import("../../components/shop/tools/product-slider.vue").default
  'ShopToolsProductTabSlider': typeof import("../../components/shop/tools/product-tab-slider.vue").default
  'ShopToolsSelectVehical': typeof import("../../components/shop/tools/select-vehical.vue").default
  'ShopToolsService': typeof import("../../components/shop/tools/service.vue").default
  'ShopToolsSlider': typeof import("../../components/shop/tools/slider.vue").default
  'ShopVegetablesBanner': typeof import("../../components/shop/vegetables/banner.vue").default
  'ShopVegetablesBlog': typeof import("../../components/shop/vegetables/blog.vue").default
  'ShopVegetablesProductSlider': typeof import("../../components/shop/vegetables/product_slider.vue").default
  'ShopVegetablesServices': typeof import("../../components/shop/vegetables/services.vue").default
  'ShopVegetablesSlider': typeof import("../../components/shop/vegetables/slider.vue").default
  'ShopVegetablesSpecialProducts': typeof import("../../components/shop/vegetables/special_products.vue").default
  'ShopWatchBlog': typeof import("../../components/shop/watch/blog.vue").default
  'ShopWatchCategory': typeof import("../../components/shop/watch/category.vue").default
  'ShopWatchCategorytabs': typeof import("../../components/shop/watch/categorytabs.vue").default
  'ShopWatchCollectionbanners': typeof import("../../components/shop/watch/collectionbanners.vue").default
  'ShopWatchInstagram': typeof import("../../components/shop/watch/instagram.vue").default
  'ShopWatchLogoSlider': typeof import("../../components/shop/watch/logo_slider.vue").default
  'ShopWatchProductSlider': typeof import("../../components/shop/watch/product_slider.vue").default
  'ShopWatchServices': typeof import("../../components/shop/watch/services.vue").default
  'ShopWatchSlider': typeof import("../../components/shop/watch/slider.vue").default
  'ShopWatchTimerBanner': typeof import("../../components/shop/watch/timer_banner.vue").default
  'ShopWatchTopProducts': typeof import("../../components/shop/watch/top_products.vue").default
  'WidgetsBreadcrumbs': typeof import("../../components/widgets/breadcrumbs.vue").default
  'WidgetsCollectionSidebar': typeof import("../../components/widgets/collection-sidebar.vue").default
  'WidgetsComparePopup': typeof import("../../components/widgets/compare-popup.vue").default
  'WidgetsHeaderWidgets': typeof import("../../components/widgets/header-widgets.vue").default
  'WidgetsLayoutSetting': typeof import("../../components/widgets/layoutSetting.vue").default
  'WidgetsLeftSidebar': typeof import("../../components/widgets/left-sidebar.vue").default
  'WidgetsNavbar': typeof import("../../components/widgets/navbar.vue").default
  'WidgetsNewsletterPopup': typeof import("../../components/widgets/newsletter-popup.vue").default
  'WidgetsProductSidebar': typeof import("../../components/widgets/product-sidebar.vue").default
  'WidgetsQuickview': typeof import("../../components/widgets/quickview.vue").default
  'WidgetsRelatedProducts': typeof import("../../components/widgets/related-products.vue").default
  'WidgetsTimer': typeof import("../../components/widgets/timer.vue").default
  'WidgetsTopbar': typeof import("../../components/widgets/topbar.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture").default
  'Icon': typeof import("../../node_modules/nuxt-icon/dist/runtime/Icon.vue").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyBlogList': LazyComponent<typeof import("../../components/blog/blog-list.vue").default>
  'LazyBlogSidebar': LazyComponent<typeof import("../../components/blog/blog-sidebar.vue").default>
  'LazyCartModalCartBottomModel': LazyComponent<typeof import("../../components/cart-modal/cart-bottom-model.vue").default>
  'LazyCartModalCartLeftModel': LazyComponent<typeof import("../../components/cart-modal/cart-left-model.vue").default>
  'LazyCartModalPopup': LazyComponent<typeof import("../../components/cart-modal/cart-modal-popup.vue").default>
  'LazyCartModalCartRightModel': LazyComponent<typeof import("../../components/cart-modal/cart-right-model.vue").default>
  'LazyCartModalCartTopModel': LazyComponent<typeof import("../../components/cart-modal/cart-top-model.vue").default>
  'LazyFooterFooter2': LazyComponent<typeof import("../../components/footer/footer2.vue").default>
  'LazyFooterFooter3': LazyComponent<typeof import("../../components/footer/footer3.vue").default>
  'LazyFooterFooter4': LazyComponent<typeof import("../../components/footer/footer4.vue").default>
  'LazyFooterFooter5': LazyComponent<typeof import("../../components/footer/footer5.vue").default>
  'LazyFooterFooter6': LazyComponent<typeof import("../../components/footer/footer6.vue").default>
  'LazyFooterFooter7': LazyComponent<typeof import("../../components/footer/footer7.vue").default>
  'LazyFooter': LazyComponent<typeof import("../../components/footer/index.vue").default>
  'LazyHeaderHeader2': LazyComponent<typeof import("../../components/header/header2.vue").default>
  'LazyHeaderHeader3': LazyComponent<typeof import("../../components/header/header3.vue").default>
  'LazyHeaderHeader4': LazyComponent<typeof import("../../components/header/header4.vue").default>
  'LazyHeaderHeader5': LazyComponent<typeof import("../../components/header/header5.vue").default>
  'LazyHeaderHeader6': LazyComponent<typeof import("../../components/header/header6.vue").default>
  'LazyHeaderHeader7': LazyComponent<typeof import("../../components/header/header7.vue").default>
  'LazyHeaderHeader8': LazyComponent<typeof import("../../components/header/header8.vue").default>
  'LazyHeader': LazyComponent<typeof import("../../components/header/index.vue").default>
  'LazyLightBox': LazyComponent<typeof import("../../components/lightBox.vue").default>
  'LazyPaymentPage': LazyComponent<typeof import("../../components/paymentPage.vue").default>
  'LazyProductBoxProductBox1': LazyComponent<typeof import("../../components/product-box/product-box1.vue").default>
  'LazyProductBoxProductBox2': LazyComponent<typeof import("../../components/product-box/product-box2.vue").default>
  'LazyProductBoxProductBox3': LazyComponent<typeof import("../../components/product-box/product-box3.vue").default>
  'LazyProductBoxProductBox4': LazyComponent<typeof import("../../components/product-box/product-box4.vue").default>
  'LazyProductBoxProductBox5': LazyComponent<typeof import("../../components/product-box/product-box5.vue").default>
  'LazyProductBoxProductBox6': LazyComponent<typeof import("../../components/product-box/product-box6.vue").default>
  'LazyProductBoxProductBox7': LazyComponent<typeof import("../../components/product-box/product-box7.vue").default>
  'LazyProductBoxProductBox8': LazyComponent<typeof import("../../components/product-box/product-box8.vue").default>
  'LazyProductBoxProductBox9': LazyComponent<typeof import("../../components/product-box/product-box9.vue").default>
  'LazySearched': LazyComponent<typeof import("../../components/searched.vue").default>
  'LazyShopBagsBanner': LazyComponent<typeof import("../../components/shop/bags/banner.vue").default>
  'LazyShopBagsBlog': LazyComponent<typeof import("../../components/shop/bags/blog.vue").default>
  'LazyShopBagsCategory': LazyComponent<typeof import("../../components/shop/bags/category.vue").default>
  'LazyShopBagsCategory2': LazyComponent<typeof import("../../components/shop/bags/category2.vue").default>
  'LazyShopBagsCategorytab': LazyComponent<typeof import("../../components/shop/bags/categorytab.vue").default>
  'LazyShopBagsInstagram': LazyComponent<typeof import("../../components/shop/bags/instagram.vue").default>
  'LazyShopBagsProductcategoryslider': LazyComponent<typeof import("../../components/shop/bags/productcategoryslider.vue").default>
  'LazyShopBagsProductslider': LazyComponent<typeof import("../../components/shop/bags/productslider.vue").default>
  'LazyShopBagsServices': LazyComponent<typeof import("../../components/shop/bags/services.vue").default>
  'LazyShopBagsSlider': LazyComponent<typeof import("../../components/shop/bags/slider.vue").default>
  'LazyShopBeautyAbout': LazyComponent<typeof import("../../components/shop/beauty/about.vue").default>
  'LazyShopBeautyBlog': LazyComponent<typeof import("../../components/shop/beauty/blog.vue").default>
  'LazyShopBeautyInstagram': LazyComponent<typeof import("../../components/shop/beauty/instagram.vue").default>
  'LazyShopBeautyProductSlider': LazyComponent<typeof import("../../components/shop/beauty/product-slider.vue").default>
  'LazyShopBeautySlider': LazyComponent<typeof import("../../components/shop/beauty/slider.vue").default>
  'LazyShopBeautyTopProductSlider': LazyComponent<typeof import("../../components/shop/beauty/top-product-slider.vue").default>
  'LazyShopBeautyVideoTutorial': LazyComponent<typeof import("../../components/shop/beauty/video-tutorial.vue").default>
  'LazyShopElectronics1CollectionBanner': LazyComponent<typeof import("../../components/shop/electronics-1/collection_banner.vue").default>
  'LazyShopElectronics1ProductTab': LazyComponent<typeof import("../../components/shop/electronics-1/product_tab.vue").default>
  'LazyShopElectronics1Slider': LazyComponent<typeof import("../../components/shop/electronics-1/slider.vue").default>
  'LazyShopFashion2Banner': LazyComponent<typeof import("../../components/shop/fashion-2/banner.vue").default>
  'LazyShopFashion2CollectionBanner': LazyComponent<typeof import("../../components/shop/fashion-2/collection-banner.vue").default>
  'LazyShopFashion2Collection': LazyComponent<typeof import("../../components/shop/fashion-2/collection.vue").default>
  'LazyShopFashion2Instagram': LazyComponent<typeof import("../../components/shop/fashion-2/instagram.vue").default>
  'LazyShopFashion2Product': LazyComponent<typeof import("../../components/shop/fashion-2/product.vue").default>
  'LazyShopFashion2Slider': LazyComponent<typeof import("../../components/shop/fashion-2/slider.vue").default>
  'LazyShopFashion3Banner': LazyComponent<typeof import("../../components/shop/fashion-3/banner.vue").default>
  'LazyShopFashion3ProductSlider': LazyComponent<typeof import("../../components/shop/fashion-3/product_slider.vue").default>
  'LazyShopFashion3ProductTab': LazyComponent<typeof import("../../components/shop/fashion-3/product_tab.vue").default>
  'LazyShopFashion3Slider': LazyComponent<typeof import("../../components/shop/fashion-3/slider.vue").default>
  'LazyShopFashionBanner': LazyComponent<typeof import("../../components/shop/fashion/banner.vue").default>
  'LazyShopFashionBlog': LazyComponent<typeof import("../../components/shop/fashion/blog.vue").default>
  'LazyShopFashionCollectionBanner': LazyComponent<typeof import("../../components/shop/fashion/collection_banner.vue").default>
  'LazyShopFashionInstagram': LazyComponent<typeof import("../../components/shop/fashion/instagram.vue").default>
  'LazyShopFashionLogoSlider': LazyComponent<typeof import("../../components/shop/fashion/logo_slider.vue").default>
  'LazyShopFashionProductSlider': LazyComponent<typeof import("../../components/shop/fashion/product_slider.vue").default>
  'LazyShopFashionProductTab': LazyComponent<typeof import("../../components/shop/fashion/product_tab.vue").default>
  'LazyShopFashionServices': LazyComponent<typeof import("../../components/shop/fashion/services.vue").default>
  'LazyShopFashionSlider': LazyComponent<typeof import("../../components/shop/fashion/slider.vue").default>
  'LazyShopFlowerBlog': LazyComponent<typeof import("../../components/shop/flower/blog.vue").default>
  'LazyShopFlowerCategoryTab': LazyComponent<typeof import("../../components/shop/flower/category_tab.vue").default>
  'LazyShopFlowerCollectionBanner': LazyComponent<typeof import("../../components/shop/flower/collection_banner.vue").default>
  'LazyShopFlowerInstagram': LazyComponent<typeof import("../../components/shop/flower/instagram.vue").default>
  'LazyShopFlowerProductSlider': LazyComponent<typeof import("../../components/shop/flower/product_slider.vue").default>
  'LazyShopFlowerServices': LazyComponent<typeof import("../../components/shop/flower/services.vue").default>
  'LazyShopFlowerSlider': LazyComponent<typeof import("../../components/shop/flower/slider.vue").default>
  'LazyShopFlowerTopProducts': LazyComponent<typeof import("../../components/shop/flower/top_products.vue").default>
  'LazyShopFurnitureBlog': LazyComponent<typeof import("../../components/shop/furniture/blog.vue").default>
  'LazyShopFurnitureCategoryTab': LazyComponent<typeof import("../../components/shop/furniture/category_tab.vue").default>
  'LazyShopFurnitureCollectionBanner': LazyComponent<typeof import("../../components/shop/furniture/collection_banner.vue").default>
  'LazyShopFurnitureParallaxBanner': LazyComponent<typeof import("../../components/shop/furniture/parallax_banner.vue").default>
  'LazyShopFurnitureSlider': LazyComponent<typeof import("../../components/shop/furniture/slider.vue").default>
  'LazyShopGymBlog': LazyComponent<typeof import("../../components/shop/gym/blog.vue").default>
  'LazyShopGymCollectionBanner': LazyComponent<typeof import("../../components/shop/gym/collection-banner.vue").default>
  'LazyShopGymInstagram': LazyComponent<typeof import("../../components/shop/gym/instagram.vue").default>
  'LazyShopGymLogoSlider': LazyComponent<typeof import("../../components/shop/gym/logo-slider.vue").default>
  'LazyShopGymProductList': LazyComponent<typeof import("../../components/shop/gym/product-list.vue").default>
  'LazyShopGymSlider': LazyComponent<typeof import("../../components/shop/gym/slider.vue").default>
  'LazyShopGymTopCollection': LazyComponent<typeof import("../../components/shop/gym/top-collection.vue").default>
  'LazyShopJewelleryCategory': LazyComponent<typeof import("../../components/shop/jewellery/category.vue").default>
  'LazyShopJewelleryInstagram': LazyComponent<typeof import("../../components/shop/jewellery/instagram.vue").default>
  'LazyShopJewelleryParallaxBanner': LazyComponent<typeof import("../../components/shop/jewellery/parallax-banner.vue").default>
  'LazyShopJewelleryProductSlider': LazyComponent<typeof import("../../components/shop/jewellery/product-slider.vue").default>
  'LazyShopJewelleryProductTab': LazyComponent<typeof import("../../components/shop/jewellery/product-tab.vue").default>
  'LazyShopJewelleryServices': LazyComponent<typeof import("../../components/shop/jewellery/services.vue").default>
  'LazyShopJewellerySlider': LazyComponent<typeof import("../../components/shop/jewellery/slider.vue").default>
  'LazyShopKidsCollectionBanner': LazyComponent<typeof import("../../components/shop/kids/collection_banner.vue").default>
  'LazyShopKidsCollectionSlider': LazyComponent<typeof import("../../components/shop/kids/collection_slider.vue").default>
  'LazyShopKidsInstagram': LazyComponent<typeof import("../../components/shop/kids/instagram.vue").default>
  'LazyShopKidsLogoSlider': LazyComponent<typeof import("../../components/shop/kids/logo_slider.vue").default>
  'LazyShopKidsParallaxBanner': LazyComponent<typeof import("../../components/shop/kids/parallax_banner.vue").default>
  'LazyShopKidsProductSlider': LazyComponent<typeof import("../../components/shop/kids/product_slider.vue").default>
  'LazyShopKidsSlider': LazyComponent<typeof import("../../components/shop/kids/slider.vue").default>
  'LazyShopPetsBlog': LazyComponent<typeof import("../../components/shop/pets/blog.vue").default>
  'LazyShopPetsCollectionBanner': LazyComponent<typeof import("../../components/shop/pets/collection-banner.vue").default>
  'LazyShopPetsLogoSlider': LazyComponent<typeof import("../../components/shop/pets/logo-slider.vue").default>
  'LazyShopPetsParallaxBanner': LazyComponent<typeof import("../../components/shop/pets/parallax-banner.vue").default>
  'LazyShopPetsProductSlider': LazyComponent<typeof import("../../components/shop/pets/product-slider.vue").default>
  'LazyShopPetsSlider': LazyComponent<typeof import("../../components/shop/pets/slider.vue").default>
  'LazyShopPetsTopCollection': LazyComponent<typeof import("../../components/shop/pets/top-collection.vue").default>
  'LazyShopShoesAbout': LazyComponent<typeof import("../../components/shop/shoes/about.vue").default>
  'LazyShopShoesBlog': LazyComponent<typeof import("../../components/shop/shoes/blog.vue").default>
  'LazyShopShoesBrand': LazyComponent<typeof import("../../components/shop/shoes/brand.vue").default>
  'LazyShopShoesCategory': LazyComponent<typeof import("../../components/shop/shoes/category.vue").default>
  'LazyShopShoesCategory2': LazyComponent<typeof import("../../components/shop/shoes/category2.vue").default>
  'LazyShopShoesCategory3': LazyComponent<typeof import("../../components/shop/shoes/category3.vue").default>
  'LazyShopShoesCollectionbanner': LazyComponent<typeof import("../../components/shop/shoes/collectionbanner.vue").default>
  'LazyShopShoesCollectionslider': LazyComponent<typeof import("../../components/shop/shoes/collectionslider.vue").default>
  'LazyShopShoesCollectiontab': LazyComponent<typeof import("../../components/shop/shoes/collectiontab.vue").default>
  'LazyShopShoesInstagram': LazyComponent<typeof import("../../components/shop/shoes/instagram.vue").default>
  'LazyShopShoesProductSlider': LazyComponent<typeof import("../../components/shop/shoes/productSlider.vue").default>
  'LazyShopShoesService': LazyComponent<typeof import("../../components/shop/shoes/service.vue").default>
  'LazyShopShoesSlider': LazyComponent<typeof import("../../components/shop/shoes/slider.vue").default>
  'LazyShopToolsAbout': LazyComponent<typeof import("../../components/shop/tools/about.vue").default>
  'LazyShopToolsCategory': LazyComponent<typeof import("../../components/shop/tools/category.vue").default>
  'LazyShopToolsLogoSlider': LazyComponent<typeof import("../../components/shop/tools/logo_slider.vue").default>
  'LazyShopToolsProductSlider': LazyComponent<typeof import("../../components/shop/tools/product-slider.vue").default>
  'LazyShopToolsProductTabSlider': LazyComponent<typeof import("../../components/shop/tools/product-tab-slider.vue").default>
  'LazyShopToolsSelectVehical': LazyComponent<typeof import("../../components/shop/tools/select-vehical.vue").default>
  'LazyShopToolsService': LazyComponent<typeof import("../../components/shop/tools/service.vue").default>
  'LazyShopToolsSlider': LazyComponent<typeof import("../../components/shop/tools/slider.vue").default>
  'LazyShopVegetablesBanner': LazyComponent<typeof import("../../components/shop/vegetables/banner.vue").default>
  'LazyShopVegetablesBlog': LazyComponent<typeof import("../../components/shop/vegetables/blog.vue").default>
  'LazyShopVegetablesProductSlider': LazyComponent<typeof import("../../components/shop/vegetables/product_slider.vue").default>
  'LazyShopVegetablesServices': LazyComponent<typeof import("../../components/shop/vegetables/services.vue").default>
  'LazyShopVegetablesSlider': LazyComponent<typeof import("../../components/shop/vegetables/slider.vue").default>
  'LazyShopVegetablesSpecialProducts': LazyComponent<typeof import("../../components/shop/vegetables/special_products.vue").default>
  'LazyShopWatchBlog': LazyComponent<typeof import("../../components/shop/watch/blog.vue").default>
  'LazyShopWatchCategory': LazyComponent<typeof import("../../components/shop/watch/category.vue").default>
  'LazyShopWatchCategorytabs': LazyComponent<typeof import("../../components/shop/watch/categorytabs.vue").default>
  'LazyShopWatchCollectionbanners': LazyComponent<typeof import("../../components/shop/watch/collectionbanners.vue").default>
  'LazyShopWatchInstagram': LazyComponent<typeof import("../../components/shop/watch/instagram.vue").default>
  'LazyShopWatchLogoSlider': LazyComponent<typeof import("../../components/shop/watch/logo_slider.vue").default>
  'LazyShopWatchProductSlider': LazyComponent<typeof import("../../components/shop/watch/product_slider.vue").default>
  'LazyShopWatchServices': LazyComponent<typeof import("../../components/shop/watch/services.vue").default>
  'LazyShopWatchSlider': LazyComponent<typeof import("../../components/shop/watch/slider.vue").default>
  'LazyShopWatchTimerBanner': LazyComponent<typeof import("../../components/shop/watch/timer_banner.vue").default>
  'LazyShopWatchTopProducts': LazyComponent<typeof import("../../components/shop/watch/top_products.vue").default>
  'LazyWidgetsBreadcrumbs': LazyComponent<typeof import("../../components/widgets/breadcrumbs.vue").default>
  'LazyWidgetsCollectionSidebar': LazyComponent<typeof import("../../components/widgets/collection-sidebar.vue").default>
  'LazyWidgetsComparePopup': LazyComponent<typeof import("../../components/widgets/compare-popup.vue").default>
  'LazyWidgetsHeaderWidgets': LazyComponent<typeof import("../../components/widgets/header-widgets.vue").default>
  'LazyWidgetsLayoutSetting': LazyComponent<typeof import("../../components/widgets/layoutSetting.vue").default>
  'LazyWidgetsLeftSidebar': LazyComponent<typeof import("../../components/widgets/left-sidebar.vue").default>
  'LazyWidgetsNavbar': LazyComponent<typeof import("../../components/widgets/navbar.vue").default>
  'LazyWidgetsNewsletterPopup': LazyComponent<typeof import("../../components/widgets/newsletter-popup.vue").default>
  'LazyWidgetsProductSidebar': LazyComponent<typeof import("../../components/widgets/product-sidebar.vue").default>
  'LazyWidgetsQuickview': LazyComponent<typeof import("../../components/widgets/quickview.vue").default>
  'LazyWidgetsRelatedProducts': LazyComponent<typeof import("../../components/widgets/related-products.vue").default>
  'LazyWidgetsTimer': LazyComponent<typeof import("../../components/widgets/timer.vue").default>
  'LazyWidgetsTopbar': LazyComponent<typeof import("../../components/widgets/topbar.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture").default>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/nuxt-icon/dist/runtime/Icon.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
