
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const BlogList: typeof import("../components/blog/blog-list.vue").default
export const BlogSidebar: typeof import("../components/blog/blog-sidebar.vue").default
export const CartModalCartBottomModel: typeof import("../components/cart-modal/cart-bottom-model.vue").default
export const CartModalCartLeftModel: typeof import("../components/cart-modal/cart-left-model.vue").default
export const CartModalPopup: typeof import("../components/cart-modal/cart-modal-popup.vue").default
export const CartModalCartRightModel: typeof import("../components/cart-modal/cart-right-model.vue").default
export const CartModalCartTopModel: typeof import("../components/cart-modal/cart-top-model.vue").default
export const FooterFooter2: typeof import("../components/footer/footer2.vue").default
export const FooterFooter3: typeof import("../components/footer/footer3.vue").default
export const FooterFooter4: typeof import("../components/footer/footer4.vue").default
export const FooterFooter5: typeof import("../components/footer/footer5.vue").default
export const FooterFooter6: typeof import("../components/footer/footer6.vue").default
export const FooterFooter7: typeof import("../components/footer/footer7.vue").default
export const Footer: typeof import("../components/footer/index.vue").default
export const HeaderHeader2: typeof import("../components/header/header2.vue").default
export const HeaderHeader3: typeof import("../components/header/header3.vue").default
export const HeaderHeader4: typeof import("../components/header/header4.vue").default
export const HeaderHeader5: typeof import("../components/header/header5.vue").default
export const HeaderHeader6: typeof import("../components/header/header6.vue").default
export const HeaderHeader7: typeof import("../components/header/header7.vue").default
export const HeaderHeader8: typeof import("../components/header/header8.vue").default
export const Header: typeof import("../components/header/index.vue").default
export const LightBox: typeof import("../components/lightBox.vue").default
export const PaymentPage: typeof import("../components/paymentPage.vue").default
export const ProductBoxProductBox1: typeof import("../components/product-box/product-box1.vue").default
export const ProductBoxProductBox2: typeof import("../components/product-box/product-box2.vue").default
export const ProductBoxProductBox3: typeof import("../components/product-box/product-box3.vue").default
export const ProductBoxProductBox4: typeof import("../components/product-box/product-box4.vue").default
export const ProductBoxProductBox5: typeof import("../components/product-box/product-box5.vue").default
export const ProductBoxProductBox6: typeof import("../components/product-box/product-box6.vue").default
export const ProductBoxProductBox7: typeof import("../components/product-box/product-box7.vue").default
export const ProductBoxProductBox8: typeof import("../components/product-box/product-box8.vue").default
export const ProductBoxProductBox9: typeof import("../components/product-box/product-box9.vue").default
export const Searched: typeof import("../components/searched.vue").default
export const ShopBagsBanner: typeof import("../components/shop/bags/banner.vue").default
export const ShopBagsBlog: typeof import("../components/shop/bags/blog.vue").default
export const ShopBagsCategory: typeof import("../components/shop/bags/category.vue").default
export const ShopBagsCategory2: typeof import("../components/shop/bags/category2.vue").default
export const ShopBagsCategorytab: typeof import("../components/shop/bags/categorytab.vue").default
export const ShopBagsInstagram: typeof import("../components/shop/bags/instagram.vue").default
export const ShopBagsProductcategoryslider: typeof import("../components/shop/bags/productcategoryslider.vue").default
export const ShopBagsProductslider: typeof import("../components/shop/bags/productslider.vue").default
export const ShopBagsServices: typeof import("../components/shop/bags/services.vue").default
export const ShopBagsSlider: typeof import("../components/shop/bags/slider.vue").default
export const ShopBeautyAbout: typeof import("../components/shop/beauty/about.vue").default
export const ShopBeautyBlog: typeof import("../components/shop/beauty/blog.vue").default
export const ShopBeautyInstagram: typeof import("../components/shop/beauty/instagram.vue").default
export const ShopBeautyProductSlider: typeof import("../components/shop/beauty/product-slider.vue").default
export const ShopBeautySlider: typeof import("../components/shop/beauty/slider.vue").default
export const ShopBeautyTopProductSlider: typeof import("../components/shop/beauty/top-product-slider.vue").default
export const ShopBeautyVideoTutorial: typeof import("../components/shop/beauty/video-tutorial.vue").default
export const ShopElectronics1CollectionBanner: typeof import("../components/shop/electronics-1/collection_banner.vue").default
export const ShopElectronics1ProductTab: typeof import("../components/shop/electronics-1/product_tab.vue").default
export const ShopElectronics1Slider: typeof import("../components/shop/electronics-1/slider.vue").default
export const ShopFashion2Banner: typeof import("../components/shop/fashion-2/banner.vue").default
export const ShopFashion2CollectionBanner: typeof import("../components/shop/fashion-2/collection-banner.vue").default
export const ShopFashion2Collection: typeof import("../components/shop/fashion-2/collection.vue").default
export const ShopFashion2Instagram: typeof import("../components/shop/fashion-2/instagram.vue").default
export const ShopFashion2Product: typeof import("../components/shop/fashion-2/product.vue").default
export const ShopFashion2Slider: typeof import("../components/shop/fashion-2/slider.vue").default
export const ShopFashion3Banner: typeof import("../components/shop/fashion-3/banner.vue").default
export const ShopFashion3ProductSlider: typeof import("../components/shop/fashion-3/product_slider.vue").default
export const ShopFashion3ProductTab: typeof import("../components/shop/fashion-3/product_tab.vue").default
export const ShopFashion3Slider: typeof import("../components/shop/fashion-3/slider.vue").default
export const ShopFashionBanner: typeof import("../components/shop/fashion/banner.vue").default
export const ShopFashionBlog: typeof import("../components/shop/fashion/blog.vue").default
export const ShopFashionCollectionBanner: typeof import("../components/shop/fashion/collection_banner.vue").default
export const ShopFashionInstagram: typeof import("../components/shop/fashion/instagram.vue").default
export const ShopFashionLogoSlider: typeof import("../components/shop/fashion/logo_slider.vue").default
export const ShopFashionProductSlider: typeof import("../components/shop/fashion/product_slider.vue").default
export const ShopFashionProductTab: typeof import("../components/shop/fashion/product_tab.vue").default
export const ShopFashionServices: typeof import("../components/shop/fashion/services.vue").default
export const ShopFashionSlider: typeof import("../components/shop/fashion/slider.vue").default
export const ShopFlowerBlog: typeof import("../components/shop/flower/blog.vue").default
export const ShopFlowerCategoryTab: typeof import("../components/shop/flower/category_tab.vue").default
export const ShopFlowerCollectionBanner: typeof import("../components/shop/flower/collection_banner.vue").default
export const ShopFlowerInstagram: typeof import("../components/shop/flower/instagram.vue").default
export const ShopFlowerProductSlider: typeof import("../components/shop/flower/product_slider.vue").default
export const ShopFlowerServices: typeof import("../components/shop/flower/services.vue").default
export const ShopFlowerSlider: typeof import("../components/shop/flower/slider.vue").default
export const ShopFlowerTopProducts: typeof import("../components/shop/flower/top_products.vue").default
export const ShopFurnitureBlog: typeof import("../components/shop/furniture/blog.vue").default
export const ShopFurnitureCategoryTab: typeof import("../components/shop/furniture/category_tab.vue").default
export const ShopFurnitureCollectionBanner: typeof import("../components/shop/furniture/collection_banner.vue").default
export const ShopFurnitureParallaxBanner: typeof import("../components/shop/furniture/parallax_banner.vue").default
export const ShopFurnitureSlider: typeof import("../components/shop/furniture/slider.vue").default
export const ShopGymBlog: typeof import("../components/shop/gym/blog.vue").default
export const ShopGymCollectionBanner: typeof import("../components/shop/gym/collection-banner.vue").default
export const ShopGymInstagram: typeof import("../components/shop/gym/instagram.vue").default
export const ShopGymLogoSlider: typeof import("../components/shop/gym/logo-slider.vue").default
export const ShopGymProductList: typeof import("../components/shop/gym/product-list.vue").default
export const ShopGymSlider: typeof import("../components/shop/gym/slider.vue").default
export const ShopGymTopCollection: typeof import("../components/shop/gym/top-collection.vue").default
export const ShopJewelleryCategory: typeof import("../components/shop/jewellery/category.vue").default
export const ShopJewelleryInstagram: typeof import("../components/shop/jewellery/instagram.vue").default
export const ShopJewelleryParallaxBanner: typeof import("../components/shop/jewellery/parallax-banner.vue").default
export const ShopJewelleryProductSlider: typeof import("../components/shop/jewellery/product-slider.vue").default
export const ShopJewelleryProductTab: typeof import("../components/shop/jewellery/product-tab.vue").default
export const ShopJewelleryServices: typeof import("../components/shop/jewellery/services.vue").default
export const ShopJewellerySlider: typeof import("../components/shop/jewellery/slider.vue").default
export const ShopKidsCollectionBanner: typeof import("../components/shop/kids/collection_banner.vue").default
export const ShopKidsCollectionSlider: typeof import("../components/shop/kids/collection_slider.vue").default
export const ShopKidsInstagram: typeof import("../components/shop/kids/instagram.vue").default
export const ShopKidsLogoSlider: typeof import("../components/shop/kids/logo_slider.vue").default
export const ShopKidsParallaxBanner: typeof import("../components/shop/kids/parallax_banner.vue").default
export const ShopKidsProductSlider: typeof import("../components/shop/kids/product_slider.vue").default
export const ShopKidsSlider: typeof import("../components/shop/kids/slider.vue").default
export const ShopPetsBlog: typeof import("../components/shop/pets/blog.vue").default
export const ShopPetsCollectionBanner: typeof import("../components/shop/pets/collection-banner.vue").default
export const ShopPetsLogoSlider: typeof import("../components/shop/pets/logo-slider.vue").default
export const ShopPetsParallaxBanner: typeof import("../components/shop/pets/parallax-banner.vue").default
export const ShopPetsProductSlider: typeof import("../components/shop/pets/product-slider.vue").default
export const ShopPetsSlider: typeof import("../components/shop/pets/slider.vue").default
export const ShopPetsTopCollection: typeof import("../components/shop/pets/top-collection.vue").default
export const ShopShoesAbout: typeof import("../components/shop/shoes/about.vue").default
export const ShopShoesBlog: typeof import("../components/shop/shoes/blog.vue").default
export const ShopShoesBrand: typeof import("../components/shop/shoes/brand.vue").default
export const ShopShoesCategory: typeof import("../components/shop/shoes/category.vue").default
export const ShopShoesCategory2: typeof import("../components/shop/shoes/category2.vue").default
export const ShopShoesCategory3: typeof import("../components/shop/shoes/category3.vue").default
export const ShopShoesCollectionbanner: typeof import("../components/shop/shoes/collectionbanner.vue").default
export const ShopShoesCollectionslider: typeof import("../components/shop/shoes/collectionslider.vue").default
export const ShopShoesCollectiontab: typeof import("../components/shop/shoes/collectiontab.vue").default
export const ShopShoesInstagram: typeof import("../components/shop/shoes/instagram.vue").default
export const ShopShoesProductSlider: typeof import("../components/shop/shoes/productSlider.vue").default
export const ShopShoesService: typeof import("../components/shop/shoes/service.vue").default
export const ShopShoesSlider: typeof import("../components/shop/shoes/slider.vue").default
export const ShopToolsAbout: typeof import("../components/shop/tools/about.vue").default
export const ShopToolsCategory: typeof import("../components/shop/tools/category.vue").default
export const ShopToolsLogoSlider: typeof import("../components/shop/tools/logo_slider.vue").default
export const ShopToolsProductSlider: typeof import("../components/shop/tools/product-slider.vue").default
export const ShopToolsProductTabSlider: typeof import("../components/shop/tools/product-tab-slider.vue").default
export const ShopToolsSelectVehical: typeof import("../components/shop/tools/select-vehical.vue").default
export const ShopToolsService: typeof import("../components/shop/tools/service.vue").default
export const ShopToolsSlider: typeof import("../components/shop/tools/slider.vue").default
export const ShopVegetablesBanner: typeof import("../components/shop/vegetables/banner.vue").default
export const ShopVegetablesBlog: typeof import("../components/shop/vegetables/blog.vue").default
export const ShopVegetablesProductSlider: typeof import("../components/shop/vegetables/product_slider.vue").default
export const ShopVegetablesServices: typeof import("../components/shop/vegetables/services.vue").default
export const ShopVegetablesSlider: typeof import("../components/shop/vegetables/slider.vue").default
export const ShopVegetablesSpecialProducts: typeof import("../components/shop/vegetables/special_products.vue").default
export const ShopWatchBlog: typeof import("../components/shop/watch/blog.vue").default
export const ShopWatchCategory: typeof import("../components/shop/watch/category.vue").default
export const ShopWatchCategorytabs: typeof import("../components/shop/watch/categorytabs.vue").default
export const ShopWatchCollectionbanners: typeof import("../components/shop/watch/collectionbanners.vue").default
export const ShopWatchInstagram: typeof import("../components/shop/watch/instagram.vue").default
export const ShopWatchLogoSlider: typeof import("../components/shop/watch/logo_slider.vue").default
export const ShopWatchProductSlider: typeof import("../components/shop/watch/product_slider.vue").default
export const ShopWatchServices: typeof import("../components/shop/watch/services.vue").default
export const ShopWatchSlider: typeof import("../components/shop/watch/slider.vue").default
export const ShopWatchTimerBanner: typeof import("../components/shop/watch/timer_banner.vue").default
export const ShopWatchTopProducts: typeof import("../components/shop/watch/top_products.vue").default
export const WidgetsBreadcrumbs: typeof import("../components/widgets/breadcrumbs.vue").default
export const WidgetsCollectionSidebar: typeof import("../components/widgets/collection-sidebar.vue").default
export const WidgetsComparePopup: typeof import("../components/widgets/compare-popup.vue").default
export const WidgetsHeaderWidgets: typeof import("../components/widgets/header-widgets.vue").default
export const WidgetsLayoutSetting: typeof import("../components/widgets/layoutSetting.vue").default
export const WidgetsLeftSidebar: typeof import("../components/widgets/left-sidebar.vue").default
export const WidgetsNavbar: typeof import("../components/widgets/navbar.vue").default
export const WidgetsNewsletterPopup: typeof import("../components/widgets/newsletter-popup.vue").default
export const WidgetsProductSidebar: typeof import("../components/widgets/product-sidebar.vue").default
export const WidgetsQuickview: typeof import("../components/widgets/quickview.vue").default
export const WidgetsRelatedProducts: typeof import("../components/widgets/related-products.vue").default
export const WidgetsTimer: typeof import("../components/widgets/timer.vue").default
export const WidgetsTopbar: typeof import("../components/widgets/topbar.vue").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img").default
export const NuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture").default
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue").default
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyBlogList: LazyComponent<typeof import("../components/blog/blog-list.vue").default>
export const LazyBlogSidebar: LazyComponent<typeof import("../components/blog/blog-sidebar.vue").default>
export const LazyCartModalCartBottomModel: LazyComponent<typeof import("../components/cart-modal/cart-bottom-model.vue").default>
export const LazyCartModalCartLeftModel: LazyComponent<typeof import("../components/cart-modal/cart-left-model.vue").default>
export const LazyCartModalPopup: LazyComponent<typeof import("../components/cart-modal/cart-modal-popup.vue").default>
export const LazyCartModalCartRightModel: LazyComponent<typeof import("../components/cart-modal/cart-right-model.vue").default>
export const LazyCartModalCartTopModel: LazyComponent<typeof import("../components/cart-modal/cart-top-model.vue").default>
export const LazyFooterFooter2: LazyComponent<typeof import("../components/footer/footer2.vue").default>
export const LazyFooterFooter3: LazyComponent<typeof import("../components/footer/footer3.vue").default>
export const LazyFooterFooter4: LazyComponent<typeof import("../components/footer/footer4.vue").default>
export const LazyFooterFooter5: LazyComponent<typeof import("../components/footer/footer5.vue").default>
export const LazyFooterFooter6: LazyComponent<typeof import("../components/footer/footer6.vue").default>
export const LazyFooterFooter7: LazyComponent<typeof import("../components/footer/footer7.vue").default>
export const LazyFooter: LazyComponent<typeof import("../components/footer/index.vue").default>
export const LazyHeaderHeader2: LazyComponent<typeof import("../components/header/header2.vue").default>
export const LazyHeaderHeader3: LazyComponent<typeof import("../components/header/header3.vue").default>
export const LazyHeaderHeader4: LazyComponent<typeof import("../components/header/header4.vue").default>
export const LazyHeaderHeader5: LazyComponent<typeof import("../components/header/header5.vue").default>
export const LazyHeaderHeader6: LazyComponent<typeof import("../components/header/header6.vue").default>
export const LazyHeaderHeader7: LazyComponent<typeof import("../components/header/header7.vue").default>
export const LazyHeaderHeader8: LazyComponent<typeof import("../components/header/header8.vue").default>
export const LazyHeader: LazyComponent<typeof import("../components/header/index.vue").default>
export const LazyLightBox: LazyComponent<typeof import("../components/lightBox.vue").default>
export const LazyPaymentPage: LazyComponent<typeof import("../components/paymentPage.vue").default>
export const LazyProductBoxProductBox1: LazyComponent<typeof import("../components/product-box/product-box1.vue").default>
export const LazyProductBoxProductBox2: LazyComponent<typeof import("../components/product-box/product-box2.vue").default>
export const LazyProductBoxProductBox3: LazyComponent<typeof import("../components/product-box/product-box3.vue").default>
export const LazyProductBoxProductBox4: LazyComponent<typeof import("../components/product-box/product-box4.vue").default>
export const LazyProductBoxProductBox5: LazyComponent<typeof import("../components/product-box/product-box5.vue").default>
export const LazyProductBoxProductBox6: LazyComponent<typeof import("../components/product-box/product-box6.vue").default>
export const LazyProductBoxProductBox7: LazyComponent<typeof import("../components/product-box/product-box7.vue").default>
export const LazyProductBoxProductBox8: LazyComponent<typeof import("../components/product-box/product-box8.vue").default>
export const LazyProductBoxProductBox9: LazyComponent<typeof import("../components/product-box/product-box9.vue").default>
export const LazySearched: LazyComponent<typeof import("../components/searched.vue").default>
export const LazyShopBagsBanner: LazyComponent<typeof import("../components/shop/bags/banner.vue").default>
export const LazyShopBagsBlog: LazyComponent<typeof import("../components/shop/bags/blog.vue").default>
export const LazyShopBagsCategory: LazyComponent<typeof import("../components/shop/bags/category.vue").default>
export const LazyShopBagsCategory2: LazyComponent<typeof import("../components/shop/bags/category2.vue").default>
export const LazyShopBagsCategorytab: LazyComponent<typeof import("../components/shop/bags/categorytab.vue").default>
export const LazyShopBagsInstagram: LazyComponent<typeof import("../components/shop/bags/instagram.vue").default>
export const LazyShopBagsProductcategoryslider: LazyComponent<typeof import("../components/shop/bags/productcategoryslider.vue").default>
export const LazyShopBagsProductslider: LazyComponent<typeof import("../components/shop/bags/productslider.vue").default>
export const LazyShopBagsServices: LazyComponent<typeof import("../components/shop/bags/services.vue").default>
export const LazyShopBagsSlider: LazyComponent<typeof import("../components/shop/bags/slider.vue").default>
export const LazyShopBeautyAbout: LazyComponent<typeof import("../components/shop/beauty/about.vue").default>
export const LazyShopBeautyBlog: LazyComponent<typeof import("../components/shop/beauty/blog.vue").default>
export const LazyShopBeautyInstagram: LazyComponent<typeof import("../components/shop/beauty/instagram.vue").default>
export const LazyShopBeautyProductSlider: LazyComponent<typeof import("../components/shop/beauty/product-slider.vue").default>
export const LazyShopBeautySlider: LazyComponent<typeof import("../components/shop/beauty/slider.vue").default>
export const LazyShopBeautyTopProductSlider: LazyComponent<typeof import("../components/shop/beauty/top-product-slider.vue").default>
export const LazyShopBeautyVideoTutorial: LazyComponent<typeof import("../components/shop/beauty/video-tutorial.vue").default>
export const LazyShopElectronics1CollectionBanner: LazyComponent<typeof import("../components/shop/electronics-1/collection_banner.vue").default>
export const LazyShopElectronics1ProductTab: LazyComponent<typeof import("../components/shop/electronics-1/product_tab.vue").default>
export const LazyShopElectronics1Slider: LazyComponent<typeof import("../components/shop/electronics-1/slider.vue").default>
export const LazyShopFashion2Banner: LazyComponent<typeof import("../components/shop/fashion-2/banner.vue").default>
export const LazyShopFashion2CollectionBanner: LazyComponent<typeof import("../components/shop/fashion-2/collection-banner.vue").default>
export const LazyShopFashion2Collection: LazyComponent<typeof import("../components/shop/fashion-2/collection.vue").default>
export const LazyShopFashion2Instagram: LazyComponent<typeof import("../components/shop/fashion-2/instagram.vue").default>
export const LazyShopFashion2Product: LazyComponent<typeof import("../components/shop/fashion-2/product.vue").default>
export const LazyShopFashion2Slider: LazyComponent<typeof import("../components/shop/fashion-2/slider.vue").default>
export const LazyShopFashion3Banner: LazyComponent<typeof import("../components/shop/fashion-3/banner.vue").default>
export const LazyShopFashion3ProductSlider: LazyComponent<typeof import("../components/shop/fashion-3/product_slider.vue").default>
export const LazyShopFashion3ProductTab: LazyComponent<typeof import("../components/shop/fashion-3/product_tab.vue").default>
export const LazyShopFashion3Slider: LazyComponent<typeof import("../components/shop/fashion-3/slider.vue").default>
export const LazyShopFashionBanner: LazyComponent<typeof import("../components/shop/fashion/banner.vue").default>
export const LazyShopFashionBlog: LazyComponent<typeof import("../components/shop/fashion/blog.vue").default>
export const LazyShopFashionCollectionBanner: LazyComponent<typeof import("../components/shop/fashion/collection_banner.vue").default>
export const LazyShopFashionInstagram: LazyComponent<typeof import("../components/shop/fashion/instagram.vue").default>
export const LazyShopFashionLogoSlider: LazyComponent<typeof import("../components/shop/fashion/logo_slider.vue").default>
export const LazyShopFashionProductSlider: LazyComponent<typeof import("../components/shop/fashion/product_slider.vue").default>
export const LazyShopFashionProductTab: LazyComponent<typeof import("../components/shop/fashion/product_tab.vue").default>
export const LazyShopFashionServices: LazyComponent<typeof import("../components/shop/fashion/services.vue").default>
export const LazyShopFashionSlider: LazyComponent<typeof import("../components/shop/fashion/slider.vue").default>
export const LazyShopFlowerBlog: LazyComponent<typeof import("../components/shop/flower/blog.vue").default>
export const LazyShopFlowerCategoryTab: LazyComponent<typeof import("../components/shop/flower/category_tab.vue").default>
export const LazyShopFlowerCollectionBanner: LazyComponent<typeof import("../components/shop/flower/collection_banner.vue").default>
export const LazyShopFlowerInstagram: LazyComponent<typeof import("../components/shop/flower/instagram.vue").default>
export const LazyShopFlowerProductSlider: LazyComponent<typeof import("../components/shop/flower/product_slider.vue").default>
export const LazyShopFlowerServices: LazyComponent<typeof import("../components/shop/flower/services.vue").default>
export const LazyShopFlowerSlider: LazyComponent<typeof import("../components/shop/flower/slider.vue").default>
export const LazyShopFlowerTopProducts: LazyComponent<typeof import("../components/shop/flower/top_products.vue").default>
export const LazyShopFurnitureBlog: LazyComponent<typeof import("../components/shop/furniture/blog.vue").default>
export const LazyShopFurnitureCategoryTab: LazyComponent<typeof import("../components/shop/furniture/category_tab.vue").default>
export const LazyShopFurnitureCollectionBanner: LazyComponent<typeof import("../components/shop/furniture/collection_banner.vue").default>
export const LazyShopFurnitureParallaxBanner: LazyComponent<typeof import("../components/shop/furniture/parallax_banner.vue").default>
export const LazyShopFurnitureSlider: LazyComponent<typeof import("../components/shop/furniture/slider.vue").default>
export const LazyShopGymBlog: LazyComponent<typeof import("../components/shop/gym/blog.vue").default>
export const LazyShopGymCollectionBanner: LazyComponent<typeof import("../components/shop/gym/collection-banner.vue").default>
export const LazyShopGymInstagram: LazyComponent<typeof import("../components/shop/gym/instagram.vue").default>
export const LazyShopGymLogoSlider: LazyComponent<typeof import("../components/shop/gym/logo-slider.vue").default>
export const LazyShopGymProductList: LazyComponent<typeof import("../components/shop/gym/product-list.vue").default>
export const LazyShopGymSlider: LazyComponent<typeof import("../components/shop/gym/slider.vue").default>
export const LazyShopGymTopCollection: LazyComponent<typeof import("../components/shop/gym/top-collection.vue").default>
export const LazyShopJewelleryCategory: LazyComponent<typeof import("../components/shop/jewellery/category.vue").default>
export const LazyShopJewelleryInstagram: LazyComponent<typeof import("../components/shop/jewellery/instagram.vue").default>
export const LazyShopJewelleryParallaxBanner: LazyComponent<typeof import("../components/shop/jewellery/parallax-banner.vue").default>
export const LazyShopJewelleryProductSlider: LazyComponent<typeof import("../components/shop/jewellery/product-slider.vue").default>
export const LazyShopJewelleryProductTab: LazyComponent<typeof import("../components/shop/jewellery/product-tab.vue").default>
export const LazyShopJewelleryServices: LazyComponent<typeof import("../components/shop/jewellery/services.vue").default>
export const LazyShopJewellerySlider: LazyComponent<typeof import("../components/shop/jewellery/slider.vue").default>
export const LazyShopKidsCollectionBanner: LazyComponent<typeof import("../components/shop/kids/collection_banner.vue").default>
export const LazyShopKidsCollectionSlider: LazyComponent<typeof import("../components/shop/kids/collection_slider.vue").default>
export const LazyShopKidsInstagram: LazyComponent<typeof import("../components/shop/kids/instagram.vue").default>
export const LazyShopKidsLogoSlider: LazyComponent<typeof import("../components/shop/kids/logo_slider.vue").default>
export const LazyShopKidsParallaxBanner: LazyComponent<typeof import("../components/shop/kids/parallax_banner.vue").default>
export const LazyShopKidsProductSlider: LazyComponent<typeof import("../components/shop/kids/product_slider.vue").default>
export const LazyShopKidsSlider: LazyComponent<typeof import("../components/shop/kids/slider.vue").default>
export const LazyShopPetsBlog: LazyComponent<typeof import("../components/shop/pets/blog.vue").default>
export const LazyShopPetsCollectionBanner: LazyComponent<typeof import("../components/shop/pets/collection-banner.vue").default>
export const LazyShopPetsLogoSlider: LazyComponent<typeof import("../components/shop/pets/logo-slider.vue").default>
export const LazyShopPetsParallaxBanner: LazyComponent<typeof import("../components/shop/pets/parallax-banner.vue").default>
export const LazyShopPetsProductSlider: LazyComponent<typeof import("../components/shop/pets/product-slider.vue").default>
export const LazyShopPetsSlider: LazyComponent<typeof import("../components/shop/pets/slider.vue").default>
export const LazyShopPetsTopCollection: LazyComponent<typeof import("../components/shop/pets/top-collection.vue").default>
export const LazyShopShoesAbout: LazyComponent<typeof import("../components/shop/shoes/about.vue").default>
export const LazyShopShoesBlog: LazyComponent<typeof import("../components/shop/shoes/blog.vue").default>
export const LazyShopShoesBrand: LazyComponent<typeof import("../components/shop/shoes/brand.vue").default>
export const LazyShopShoesCategory: LazyComponent<typeof import("../components/shop/shoes/category.vue").default>
export const LazyShopShoesCategory2: LazyComponent<typeof import("../components/shop/shoes/category2.vue").default>
export const LazyShopShoesCategory3: LazyComponent<typeof import("../components/shop/shoes/category3.vue").default>
export const LazyShopShoesCollectionbanner: LazyComponent<typeof import("../components/shop/shoes/collectionbanner.vue").default>
export const LazyShopShoesCollectionslider: LazyComponent<typeof import("../components/shop/shoes/collectionslider.vue").default>
export const LazyShopShoesCollectiontab: LazyComponent<typeof import("../components/shop/shoes/collectiontab.vue").default>
export const LazyShopShoesInstagram: LazyComponent<typeof import("../components/shop/shoes/instagram.vue").default>
export const LazyShopShoesProductSlider: LazyComponent<typeof import("../components/shop/shoes/productSlider.vue").default>
export const LazyShopShoesService: LazyComponent<typeof import("../components/shop/shoes/service.vue").default>
export const LazyShopShoesSlider: LazyComponent<typeof import("../components/shop/shoes/slider.vue").default>
export const LazyShopToolsAbout: LazyComponent<typeof import("../components/shop/tools/about.vue").default>
export const LazyShopToolsCategory: LazyComponent<typeof import("../components/shop/tools/category.vue").default>
export const LazyShopToolsLogoSlider: LazyComponent<typeof import("../components/shop/tools/logo_slider.vue").default>
export const LazyShopToolsProductSlider: LazyComponent<typeof import("../components/shop/tools/product-slider.vue").default>
export const LazyShopToolsProductTabSlider: LazyComponent<typeof import("../components/shop/tools/product-tab-slider.vue").default>
export const LazyShopToolsSelectVehical: LazyComponent<typeof import("../components/shop/tools/select-vehical.vue").default>
export const LazyShopToolsService: LazyComponent<typeof import("../components/shop/tools/service.vue").default>
export const LazyShopToolsSlider: LazyComponent<typeof import("../components/shop/tools/slider.vue").default>
export const LazyShopVegetablesBanner: LazyComponent<typeof import("../components/shop/vegetables/banner.vue").default>
export const LazyShopVegetablesBlog: LazyComponent<typeof import("../components/shop/vegetables/blog.vue").default>
export const LazyShopVegetablesProductSlider: LazyComponent<typeof import("../components/shop/vegetables/product_slider.vue").default>
export const LazyShopVegetablesServices: LazyComponent<typeof import("../components/shop/vegetables/services.vue").default>
export const LazyShopVegetablesSlider: LazyComponent<typeof import("../components/shop/vegetables/slider.vue").default>
export const LazyShopVegetablesSpecialProducts: LazyComponent<typeof import("../components/shop/vegetables/special_products.vue").default>
export const LazyShopWatchBlog: LazyComponent<typeof import("../components/shop/watch/blog.vue").default>
export const LazyShopWatchCategory: LazyComponent<typeof import("../components/shop/watch/category.vue").default>
export const LazyShopWatchCategorytabs: LazyComponent<typeof import("../components/shop/watch/categorytabs.vue").default>
export const LazyShopWatchCollectionbanners: LazyComponent<typeof import("../components/shop/watch/collectionbanners.vue").default>
export const LazyShopWatchInstagram: LazyComponent<typeof import("../components/shop/watch/instagram.vue").default>
export const LazyShopWatchLogoSlider: LazyComponent<typeof import("../components/shop/watch/logo_slider.vue").default>
export const LazyShopWatchProductSlider: LazyComponent<typeof import("../components/shop/watch/product_slider.vue").default>
export const LazyShopWatchServices: LazyComponent<typeof import("../components/shop/watch/services.vue").default>
export const LazyShopWatchSlider: LazyComponent<typeof import("../components/shop/watch/slider.vue").default>
export const LazyShopWatchTimerBanner: LazyComponent<typeof import("../components/shop/watch/timer_banner.vue").default>
export const LazyShopWatchTopProducts: LazyComponent<typeof import("../components/shop/watch/top_products.vue").default>
export const LazyWidgetsBreadcrumbs: LazyComponent<typeof import("../components/widgets/breadcrumbs.vue").default>
export const LazyWidgetsCollectionSidebar: LazyComponent<typeof import("../components/widgets/collection-sidebar.vue").default>
export const LazyWidgetsComparePopup: LazyComponent<typeof import("../components/widgets/compare-popup.vue").default>
export const LazyWidgetsHeaderWidgets: LazyComponent<typeof import("../components/widgets/header-widgets.vue").default>
export const LazyWidgetsLayoutSetting: LazyComponent<typeof import("../components/widgets/layoutSetting.vue").default>
export const LazyWidgetsLeftSidebar: LazyComponent<typeof import("../components/widgets/left-sidebar.vue").default>
export const LazyWidgetsNavbar: LazyComponent<typeof import("../components/widgets/navbar.vue").default>
export const LazyWidgetsNewsletterPopup: LazyComponent<typeof import("../components/widgets/newsletter-popup.vue").default>
export const LazyWidgetsProductSidebar: LazyComponent<typeof import("../components/widgets/product-sidebar.vue").default>
export const LazyWidgetsQuickview: LazyComponent<typeof import("../components/widgets/quickview.vue").default>
export const LazyWidgetsRelatedProducts: LazyComponent<typeof import("../components/widgets/related-products.vue").default>
export const LazyWidgetsTimer: LazyComponent<typeof import("../components/widgets/timer.vue").default>
export const LazyWidgetsTopbar: LazyComponent<typeof import("../components/widgets/topbar.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img").default>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture").default>
export const LazyIcon: LazyComponent<typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue").default>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
